# Generated by Django 4.1.3 on 2023-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('t_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=60)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
